deploy:
  provider: heroku
  api_key:
    secure: QYKZ9P6jk4KAmddR5FL1PUbagypWhh7nnJi0Trx9zhMNTQA7z80ZMmCkNSycGqWUaaF1aEw3ALbDSqnr/U00zIq5Mb7oaiBSCu/q/ExViLm+vkOz6Xm5vP5yPrVbB1IfEM8c4qOsvn2dn1ivFy82lLR+9v41+IJLvIwYKjk8qxU=
  app:
    master: homeappv2
    develop: homeappv2-accept
  on:
    repo: tomasharkema/HomeAppv2-Server

deploy:
  provider: heroku
  api_key:
    secure: QYKZ9P6jk4KAmddR5FL1PUbagypWhh7nnJi0Trx9zhMNTQA7z80ZMmCkNSycGqWUaaF1aEw3ALbDSqnr/U00zIq5Mb7oaiBSCu/q/ExViLm+vkOz6Xm5vP5yPrVbB1IfEM8c4qOsvn2dn1ivFy82lLR+9v41+IJLvIwYKjk8qxU=
  app: homeappv2-staging
  on:
    all_branches: true

before_script: cp config.example.json config.json

language: node_js
node_js:
  - "0.10"

notifications:
  email:
    - tomas@harkema.in

services:
  - mongodb